name: Trigger Central CI

on:
  push:
    branches: [main]

jobs:
  call-ci:
    uses: nirajan-devops/ci-workflows/.github/workflows/react.yml@main
    with:
      app_name: hello-react-app
      artifact_name: hello-react-app-build
    
